name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ]

  schedule:
    - cron: '15 6 * * SUN'

  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
      

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Output Trigger
        run: echo 'The event that triggered this event was ${{ github.event_name }}'

      - name: Output Repo
        run: echo 'The repository is ${{ github.repository }}'

      - uses: actions/checkout@v4
      - run: |
          echo "These are the files in the repository: "
          tree
  Test:
    runs-on: ubuntu-latest
    needs: Build
    environment: Test
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - run: echo "Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    environment: Load-Test
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - run: echo "Testing..."

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    if: ${{ github.events.inputs.environment == 'Production' }}
    steps:
      - run: |
          echo "Step 1 deploying..."
          sleep 10
          echo "Step 2 deploying..."
          sleep 10
          echo "Step 3 deploying..."
          sleep 10
          echo "Step 4 deploying..."
          sleep 10
          echo "Step 5 deploying..."
          sleep 10
